#! /usr/bin/ruby

`cp .bash_profile ~/.bash_profile`
`cp .gitconfig ~/.gitconfig`
`cp .bashrc ~/.bashrc`

`/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"`